# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'new', b'Products Ordered'), (b'filled', b'Orders Filled'), (b'remove', b'Taken Out of Inventory'), (b'ready', b'Order Ready for Pick Up'), (b'billing', b'Order Delivered'), (b'complete', b'Billing Complete')], default=b'new', max_length=50)),
                ('comment', models.TextField(blank=True, help_text=b'If you have any comments, please add it here', max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('client_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text=b'Drug brand of the product', max_length=200)),
                ('name', models.CharField(help_text=b'Drug name of the product', max_length=200)),
                ('strength', models.CharField(help_text=b'Product stregnth of the pack: mg, ml etc.', max_length=50)),
                ('price', models.FloatField(help_text=b'Price of the product in dollar: xx.xx')),
                ('CIN', models.IntegerField(help_text=b'CIN number of the product with digits')),
                ('description', models.TextField(blank=True, help_text=b'You can add product description here', max_length=2000, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_type', models.CharField(choices=[(b'Vendor', b'Customer'), (b'Administrator', b'Administrator')], default=b'Vendor', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_drug_brand', models.CharField(max_length=200)),
                ('shopping_drug_name', models.CharField(max_length=200)),
                ('shopping_strength', models.FloatField(max_length=50)),
                ('shopping_quantity', models.IntegerField(default=0)),
                ('client_obj_shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_drug_name', models.CharField(max_length=200)),
                ('wish_drug_brand', models.CharField(max_length=200)),
                ('wish_drug_strength', models.CharField(max_length=50)),
                ('wish_drug_price', models.FloatField(max_length=50)),
                ('client_obj_wish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_To_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WTO_drug_name', models.CharField(max_length=200)),
                ('WTO_drug_brand', models.CharField(max_length=200)),
                ('WTO_drug_strength', models.CharField(max_length=50)),
                ('client_obj_WTO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='order_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.Order'),
        ),
    ]
