# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='i.e. david', max_length=100)),
                ('phone_number', models.IntegerField(default='i.e. 7651111111')),
                ('contact_email', models.CharField(default='i.e. david@purdue.edu', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='i.e. Decodron', max_length=200)),
                ('name', models.CharField(help_text='i.e. Amoxicillin', max_length=200)),
                ('strength', models.CharField(help_text='i.e. 500ml', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New order'), ('filled', 'Order to be filled'), ('remove', 'Remove from inventory'), ('ready', 'Ready for pickup'), ('billing', 'Billing'), ('complete', 'Completed')], default='new', max_length=50)),
                ('comment', models.TextField(help_text='Any additional information', max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('client_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.Client')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='order_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.Order'),
        ),
    ]
